### ISSUE TITLE
PEPSI font

### ISSUE THREAD

**Issue by Fozqu** [cr4ckp0t/ElvUI_AdditionalFonts#1]
Hello. I met this issue with pepsi font applied to combat text. Language: Russian. Most likely it replaces "Промах". But few other words broken as well, not about full list.

![image](https://user-images.githubusercontent.com/6608345/102529229-48808e00-40a8-11eb-985c-b49afa0cbac5.png)

**Comment by cr4ckp0t** [comment]
This is a limitation of the Pepsi font. I cannot control its characters.
