### ISSUE TITLE
Request for additional font Lexie Readable

### ISSUE THREAD

**Issue by solagegrey** [cr4ckp0t/ElvUI_AdditionalFonts#10]
Hi - and thank you. I haven't been specifically diagnosed with dyslexia, but I've been using this font for WoW (I wrote a little addon to do it, but yours is better). It makes almost everything easier and quicker to read. I'd double-check to make sure of compliance, but the following download location says "Lexie Regular & Bold - free for personal, educational and charity use," and the Readme.txt file has this wording:

"The Regular and Bold weights of Lexie Readable are available free for personal use; these two fonts can also be used free of charge, without a licence, by educational and charitable institutions.

Licences are required for italic and heavy weights of Lexie Readable. Licences are required for business use of the Lexie Readable family –
http://www.k-type.com/licences"

https://www.k-type.com/freefonts/LEXIE_READABLE_REGULAR_BOLD.zip

**Comment by cr4ckp0t** [comment]
I added the fonts to version 1.7.7.
