### ISSUE TITLE
Font Request: Inter

### ISSUE THREAD

**Issue by bynickrich** [cr4ckp0t/ElvUI_AdditionalFonts#5]
It would be awesome if you could add the open source font Inter to this list!

**Comment by cr4ckp0t** [comment]
Sure, look for it in the next version.

**Comment by bynickrich** [comment]
Awesome thank you! Really appreciate it!

**Comment by cr4ckp0t** [comment]
Done! Look for version 1.5.0 on Curse in the next couple of hours.

**Comment by bynickrich** [comment]
Woo sweet! Thanks again!
